name: mekong_hydrology
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - ipywidgets
  - matplotlib
  - pysal
  - geopandas
  - shapely
  - pandas
  - numpy
  - seaborn
  - plotly 

  - python=3.8
  - pip






